name: Unbound DNS
version: "1.25.1"
slug: unbound
description: >-
  A validating, recursive, and caching DNS resolver
url: "https://github.com/DCx91/ha-addons/unbound"
arch:
  - aarch64
  - amd64
startup: system
init: false
image: ghcr.io/dcx91/unbound
ports:
  5335/udp: 5335
  5335/tcp: 5335
map:
  - addon_config:rw
apparmor: true
options:
  do_ipv6: false
  log_level: 1
  num_threads: 1
schema:
  do_ipv6: bool
  log_level: list(0|1|2|3|4|5)
  num_threads: int(1,32)
  no_persist_cache: bool?
  cache_min_ttl: int(0,3600)?
  cache_max_ttl: int(60,604800)?
  access_control:
    - str?
  custom_config: str?
