name: Unbound DNS
version: "1.24.2"
slug: unbound
description: >-
  A validating, recursive, and caching DNS resolver
url: "https://github.com/DCx91/ha-addons/unbound"
arch:
  - aarch64
  - amd64
startup: system
init: false
ports:
  5335/udp: 5335
  5335/tcp: 5335
map:
  - addon_config:rw
apparmor: true
options:
  log_level: "1 - Operational"
  listen_port: 5335
  do_ipv6: false
  num_threads: 1
  access_control:
    - "10.0.0.0/8 allow"
    - "127.0.0.0/8 allow"
    - "172.16.0.0/12 allow"
    - "172.30.0.0/16 allow"
    - "192.168.0.0/16 allow"
schema:
  log_level: list(0 - Error|1 - Operational|2 - Detailed|3 - Query|4 - Algorithm|5 - Cache Misses)?
  listen_port: int(1,65535)
  do_ipv6: bool
  num_threads: int(1,32)
  access_control:
    - str
  hyperlocal: bool?
  persist_cache: bool?
  cache_min_ttl: int(0,3600)?
  cache_max_ttl: int(60,604800)?
  custom_config: str?
