name: AIOMetadata
version: "3.4.1"
slug: aiometadata
description: >-
  Aggregates and enriches movie, series, and anime metadata from multiple sources,
  giving you full control over catalog sources, artwork, and search.
url: https://github.com/DCx91/ha-addons/aiostreams
arch:
  - amd64
  - aarch64
init: false
ports:
  3232/tcp: 3232
ports_description:
  3232/tcp: AIOMetadata Web UI
webui: http://[HOST]:[PORT:3232]
options:
  host_name: ""
  tmdb_api_key: ""
  single_user: true
  poster_cache: true
  verbosity: Info
schema:
  host_name: url
  tmdb_api_key: str
  single_user: bool
  poster_cache: bool
  verbosity: list(Silent|Info|Debug)
  admin_key: password?
  tvdb_api_key: str?
  fanart_api_key: str?
  rpdb_api_key: str?
  warming_uuids: 
    - str?